Repository qubitsnepal/todo-app, pull requests merged in 2020-09, with the labels that each got.

#33 Signup form formik
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/ErrorMsg.js
  src/components/SignUpForm.js
Labels: frontend

#34 include formik on todo app
  README.md
  src/App.js
  src/components/SignInForm.js
Labels: frontend

#36 Modify todoform using formik
  src/components/SignUpForm.js
  src/components/Task.js
  src/components/TaskList.js
  src/components/TodoForm.js
Labels: enhancement, frontend

#38 Modify todoform using formik
  src/components/Task.js
  src/components/TaskList.js
  src/components/TodoForm.js
Labels: enhancement, frontend

#40 setup Redux Toolkit
  package-lock.json
  package.json
  src/Reducers/Reducer.js
  src/Reducers/RootReducer.js
  src/Store/Store.js
Labels: enhancement, frontend

#43 Implement Redux Toolkit
  src/App.js
  src/Reducers/Reducer.js
  src/Reducers/RootReducer.js
  src/Store/Store.js
  src/components/Task.js
  src/components/TodoForm.js
  src/features/todoSlice.js
Labels: enhancement

#44 Update delete clear using rtk
  package-lock.json
  package.json
  src/components/Task.js
  src/components/TaskList.js
  src/components/TodoForm.js
  src/contexts/GlobalContext/GlobalContext.js
  src/contexts/GlobalContext/GlobalProvider.js
  src/features/todoSlice.js
  src/store/store.js
Labels: enhancement, frontend
